name: Build

on: [ push ]

jobs:
  macOS-10-15-AppleClang:
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install dependencies on macOS
        run: brew install cmake
      - name: Build
        run: cmake . && make

  macOS-11-6-AppleClang:
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install dependencies on macOS
        run: brew install cmake
      - name: Build
        run: cmake . && make
